### ISSUE TITLE
Embed the program in a readable pretty deep link?

### ISSUE THREAD

**Issue by breck7** [tone-row/flowchart-fun#103]
Instead of:

```
https://flowchart.fun/c/NoZwLghgTmC6AEAjArgSwDYBMByBTA7gEwAiAMhAHYDmyEVuAUPAA4D24AggApStVQQAtgBVWALnjwAQqjABhdK2Rgm8dLmgUJACnDQwASiA
```

Have you thought about just including the url encoded contensts?

```
https://jtree.treenotation.org/sandbox/#tree%0A%20%5Bstart%5D%20buildNew2DLanguage%0A%20%20postAProgramTo%3A%20%20BitClout%0A%20%20%20learn%3A%20(start)
```

A related lib: https://github.com/breck7/patch

**Comment by rob-gordon** [comment]
Yep, that's how it worked before. We switched to compression because larger flowcharts were failing because of url length. Check out https://github.com/tone-row/flowchart-fun/issues/98

**Comment by breck7** [comment]
Interesting! Thanks for the context.

Have you thought about also adding support for client side only deep links? You can have thousands of characters in the "#" portion of the link no problem.

**Comment by rob-gordon** [comment]
> client side only deep links

I'm not sure I know what that is 😅  
Is it different than a normal url?

**Comment by breck7** [comment]
When you visit `server.com/index.html#foo`, the browser does not send the hash `#fee` in the get request. So "client side only deep links" are a nice secure way for users to save shareable programs that don't get sent over the wires.

**Comment by rob-gordon** [comment]
Switching to the hash seems like a win-win in terms of privacy and not hitting server limits for url lengths. I'm able to share [a chart with 2000 lines](https://deploy-preview-112--agitated-knuth-acd401.netlify.app/c#H4hQBsEME8HsFcAuAuUACNA7SBbApsmgE6SYAmsO6xpA1gCICWRhAMgEqgjCgAqAFowDOaSAAcxaAO6witEQCNoaRNDGNMAc2oBJcnkyINmtAGMieSIjwjIacBtorYK-njPwiFw-Y15qpMrWAB4oaAp4AGay7namsOCwmGYWVjai9pAR4NQAwqnWGQ6YTmTMeKaI4MrwQsau7njBkJWZ2SpNiNQYDrTuiIJChAAUAsKiEtKy8uFBasYAlN1oANqmtYiUaDr0ALposssYSqJkZVqiySs7+6RkxFF43qb1A1ZHGL59rsIj60KbHDbegLNAAejBaAAmggzKRROAhC5au46lpwHgALTFdzxHD4QxCPiDCaSGRyRRzdRaXT6Qz1cyWay2XwlZwNDxeAyIVn+DCBDqhQgRaIWDLxRLJRlpFlQbJ5AqxVmlcqVapoWqvNxoJotHlyvDgQVdT5ffqDEZjWyTckzE6qamaJamtYbLY3A5ED4nSBnerw657S73CyRJ4GF4XN4m02fXrm35oYb-QHA0EQ6Gw0zwyCI5FCVHGDHYvxmSgExBEq2kqYU2YqeY0jB6MjchmK2WOdkDXGebz6vwBTBBTrCqIxcUJJIpJnpOwGnIYfKzopdsoWNU1NEmHs65qtBfG5bxn5DJPV8Rk6aUhuO52fV0A91Bw6x+u+84mAMeu4PMPPLV3jfHpGG+AZE2TN0gR2dNIRheA4WSXMkQ1As0G3YscTLfFuSrElL1rO0qWMWlW3pC5pWZVc2U2Dl1i5HwcSHEchXCccxTiKcpQ7IoskNBUV3nNdVSqLctUafd9T4o0QhjECwItc98Jta96wdRZlkfVMPVfWMfT9C5vyDX9Q3DTBIx3fggOAk9wLPSCn2gkFwTgrMczzVDC3RLEsLxCs8PGAjbRvdSm22OkjAonihJolxd3o-teWY40x1FJUJWnSi5zafil0VaiVQ3UTUPEvc9RymTOmPUCE3si8VLre1GydTSU2ffZdNNfTP0uVYf3IP8zIs1xrLfWzFIc7TnIzeDEIRFCUXQosfNLPzcOJQKGqI28SObCL21nTtYrovtuSS-lhxSti0snSUZxlXj5TywTlTQdcKmKzUo21XUD2ko9TXGiD6qvRriK0e8MC09rPW9ZQP39K5+pDR4AO+0bYyB+y2qc2DMwQ7MkI8xaMJWzBcXLdaQcIkLmtItsosOgru21BKzqYi6WLCEUJ04u6stlaSBLSZn3s3Ervok8rD1k6qFOB5TQe20KWpdHHgQ6r0326xG+uMgbTLRyyMcBmrTz+KC0xc-G5uQ-MvM0TDVspwkNutJXacdenyJMAXmdo+LTsYwdOaunmOLLfnooq4XChiwqPvVL7LKlv72ll035bqxWabU5rIdWdWdK1vT4YMr8kf1lH-wjQC5Mxs27ItxyrZmtyiYWtDSZLcnsP8t2a2CvOvb2sjIt96PiicAPWaDgdyeS2TUt5yPMsnoXnpF+O3pEpPtw5X6pPTqrM9qy0c6Hpq71ay3i7h04eqM24DdR2v0fr0-zaTIvptcgn3M7g7J2vc1qu2ppfcG2hR4MwnkzbeM9ewMXnnyS4XNl4RwytxOBMdN5x1emLT6+9dyHwqgDOMjcJrgNUlfDSatb4vhLl1Muj9K7P2rkNOuHx5Jn2-vQvGs1CbzXtktbyPcKY4TARfahkDvbj3ulReBcVZ5IPOqgsO7F0pcXkdlBcsclRTx3kVPepUSEyxPuQrO59Noe2HrQh8P9Nb3wRoZVhwZBpGxGh-CxPDJrPn4e3IRnkRGOzJuI-uVCwY7TCi2GB2ijrTyUYgxKHM1FL2uivTBcTHq5TQMuLe+Dd5iUlmVNOhoyHcK-qMKRkSVYF2hk5Rx2tmG60DGw9xb9jZeIqU3XhLcYLWwEQA4R3dfIu0rAPIK0iolQPCmPA6D1FEnRUSkgUaTw6aKjtg3RuD9HCSMUUlOJSj5lIzt4ypETlb5xvn0hhTjy69VaW4w2HTPFcLNJUn+-j-4d2GctMRfcqbVMuSPWZsS-aLMDsskOqTRzpIwVo8FODcn5W3gQ4xxTTH-VOd0yhQLPZ2Khg42GTSH4tORu08ynDgLvJ6b43GAyAl2yCSM52EjxkXPxdE-ajMFmvQQZyZJ0LVmwvWbdNeWyN7IpegYtFByD6SVIdimluLrG5xoRDa5U1Gml1JS4vWbTnmUvfm8rGzcppfNtsTLufzRlsoCu7NVMjoE+yyRC5RgqF6hzWRosVWDeXbKlfkmVhSJaHMxcfUIcsfEctsRquhNztVMN1RXfVTzX5Gs6SaihEFPkMu+YEkmNrWXhLxbGmZMSXWIoMfytmwdPUwtYqKvm4r-WSryXg4N+zQ3yulli8xOKFaqogdMupRLOqfB1nqx5Jl03DWjFmyxvTzV5stYA4JwCwmAqHVMlWsj5kKL5YkgV7MhWXW9TdZtfqD0Bvbbstksru3EIVWYyNn9aUxvVarex9DE0TuaVO8lhq51WS6cqnNfCV2CKZYW0RtqS3bpqXTZ1ciq1dhrXPVRwrG0+sva6pFt7RYhuTj20plVX1nPfaWz9o6f3Ep1c4lN06X41wza86lpql1+Mg0M5lRaQFjPtYPHdSHQWVsnmho9tbkGLxFTh1eV6dFtpRQUrtxGn29ojfXDjVSEPAoJYXWj47jj-sY4B2dVKbLZuxhBtu+boPWtg8WrdDrh27uQ-unREmlkepQVh7mcnMlVqU9KvZic5XqdI+UsD2ddOcq-YSwzjC-3JoeWZljwGTYUYmrm2zq7fmOf43aiZW04t7p5derzkKfMyewxe+TeGb3Kc7WFx9P1n19vIwOmLLnhPX3jVqujSaGOparhSjLoHtM5b-nl3jBXN2SNi2WsrsD-WVfdSe+tfn0EbJbde4LQbQvizU21jTJz+3RasT1xDfXv0JsG8l4bT803pYs2NKzZquO5ag1aoBoSAULau3prlczyueeOlVjbvmz2ybq4F9eT1A0dsO4Qkx7XNNRvOVRyBNG7tGffPcp7M6XvGvY+9zj9Kvs8ZgyE-5oD2VY+mcthra2kmQ5q-52HCL4c5II6iojRCTuRaVdpj92PNUwzx5O0zo2gOvYbouulrdpvfbXSywr8HAelfc6D+JLNWd1qh2guFO2FOCwR7zlTLXjup2OWRrTZOdOa7LTjgbkuTMjYNeZknlmFdTZtir-LNO4POaE9d3aomUPifB+tg37Ptu+oa-tpH97+eo9O3bjHlHFvUfFw0+7xmUuE+Yxw73b3fc2eV1ThzQenMA9D0D8t3KVsVej-r6TXqYcZK5xK83TXkforDWjs7nWLtKWz2L-rEuksF8e64onJfM2k-Lzci1AfZs1-VyHyZYfgdgqjwk7zbOO+1a75s1tveQsp9UwLm3irzsi4Z7U3PGt8-45Yam+fHj51L58X7wZPz18N1-t6dx9Gdtdm8wcD8IdY9j8OdT9dtFML8Dsr8rcb8jk78R8H9QCn9J8883dC859i8v8QMF1f8K9-cq9ftacBNisbFP0mdUNW9j0YCG04D4Uz89skDk8E4js0Dw1h97cFdRcR1n874SVZ8P8iCXlv8fcyCV9uMADqcgC6dBNt8G8GD989dmD29WD49cMgsuC70eCUcMUh8M830VUncc9cCX98CJCmN2FiDMsusPsKdK9FDq9lCaDhC3MI8PNdd0MoVNtocT92CECzcec+8UDeC08hd78HcfCrkbCxD6MCdCDHDpCSCf8PlyD-8C1PC-sVDaDHUwC-Cdd-ZJMMMVkQi2CTdE9DDCNr9YjbcossCrCJ9btXdp838yUZcvdF9ZCcj5DKcPCqDg8681CtcyiICAjKigjDd1FOcODEDIjL9jCB8SMWjhcEjH8kjOip87l38HCxs5cLDwNhj3D8ixja8QD2jSiK1I8tkWdtDMMai9D6sDDVjkD1jwtBctj4ihDdibsEtcduipcPdnsF82NBjaU-9GUft11CjvCgTw8Hj-CKjD8WCttjcE9PjFxEcjDDFUDmiMDBDo0US419i8CwT3ci8MjWMZCy85Dl0RirjETqCitEiQU0Tyi3U29Xijcm0Pjud8SLdmsYjTD09WidjsC9iQSujDjejPdicBimShiWTLj7NrjN8JiSsltwDmcmCpMBTFj4DTdslRSoifjWtb8X0yTMdZTgSDNQTFSAM+iVToS1TYTcj4TVc+N5tbj68pieSZiMToCdDsShS4ce8vjuCiSJTB8pTtjATHT9N6lbCaSCDJD6TxtSD1TPtNSES1cAzVC9T6CDTGCoCY8Iy3icT9CRS9FGjiTJS4jMCZS7icCqSMzXTpdlSoTGT5dmSCyKDRj2TxjAzJj9TpjDSqz+TqjBSAtu9z9YzCSH1rd0C7TM9LCgzndRDblxC0jsyTjS9Bz8y3CRy2TizgDSy6CnVpzKytDjT5zTSwjzT5wk9VzU8Wz-i2yUyOy5TnSFSDyji0t+ysiYTssfS7Miz-TrzijXMRMQyZzHyqjT0FyljwiLTGy+cmjvzSStzB1-ynT0yUihtDzjjZcTyzjrMLiLytSxybibySjfCkKHzAjqtYD3jozlzLS1j4yTDEzWz7Ss8iK0yx1Mz7DQKnCJsHc4ToK-S5s4KuTUSm9kL2Kj9dC6zhSYzeLvj+KNiIsfzhLtzJzrCuzSKHtyKpLMjnDR9Fd+lWT6KryijlLd8xMnijTULgj0KzT6iVymyEzNj8LqLLsdyzL5SDjgKlTITpK8zvTaK8inLYKXKKTG8QdQy+SXjnzz1fK8TsLLdArDLgqstCKwqOiIrqSeyITP8bKZLl8NS6KYLFKUrUy3LHjVtPL5i48tLuLOD-KcLmzBKjKCLusyqRDkj9zUiQL3SwLbLJsoKZslCkTOTUqNCPLZysq0KXy6i8qdkAqBKgrNyQqx9RLKSKruyoq3S+zYrsj4qGrEqmqN8Sz4LesVL0q1K5iOLNKoyly+rdK4y1y+CzDpS-yxrOzzqLKZ8rKZqbqILzj7rfTA8vCVrWq0q991qUKurOKerfqVj-rPzcKhriqXCTqwaAKSLJqyLprrraq4rIKErEbADlqNcybuTVK2LPqNLIzFzliIj8b9qDK-jia7LXL4tALIqproqaqGTwKvT6aEb5Kkbmat8yy7zWLND1KsTayfreasK9qBrCqhajqSrRrTLyrxbKrLreyYrabbr5bhyHqFKnqlLVqKyNbOatafLXy-L+aDaDqirjaSbHdWaxLEsqq6TjzVTTy7qHbGalqOSWazb7j2b3bMSayvadqGz9aCr-ajaOtjLSqk7waLaLrJarqbaZa5rZKFq1947xymKEK2b3qOa06TScrvbdqCSBbfjbT86RrQqi7ybxLw70jI7PTo77bzzHalaE6Vbbzk7m7U7wy27O8O6s6u6-bBbe70djrg7B7iLh6rbqqpDK66qhyp646CjZ7dT56WKU6MbNb07trcT16xT+8e6Ny+7d7RaXcJaqapaT7cy7b4bY7Fambr6JzVaF70aOqNqnytr27M6dL8rxTc7t6BD+7Sb97Q6XSj6I7KKo7d65LFqr766Xqd80b3LYHMavruaMK3z8MrT9KP7+DzCTaB6oHi6Kbf0obqaK6gG4aaKFaSHtTnrRa1rqHH6V7QikGeKUH36bTP6d72GsHOGh6w68HR6CHx6iGa7KCGKdTIHb7EL77JGPan7EGX7kHs7UGt6lGMHv7Urf7Lay7rbpaBG5aQGL6wG67GLyH1C3aH7zHpHairG5GbGFH1zWGQbyTUbnHS7-7y73HTiVH7Lf5GqnbkbE61Gm6YGW84GvKFjLH6zrGN6c67HonkzYnTqxbuHX9wT8H+idHUniHa7SG-HxHAmzHW7srV7ZG-r5Hoi0H7G2Gg6f69yeGeiknAGUmg7Wn9HnLkTUaJH8maGubtaebML3yGjN6WHgaqmHSan4nIapm3GZmqKWm9HRzFmUaamVnIC1nPbn6SnwmynbG9mkyATqmQ6zqS6TmGmtGmmBzdGGafH2nDGG7Xq2r0TMr4HvLnntLXm36hmKn9mvnDmfnanD7XHj6czZm7L5nrnkqlm7munVmpHemZGwmBmImUWPmhLMG96cmcGgKcXGmPTgXLnQWRGDGxHXb7yl7qyQmuLca+bBnrSom0XfzvnsHfm6m7DoaabT66avGlcMmZ6yHOmBWgmemEG+nqW8bxXmHFHKn0WRLMXjnKbLK+HkmLm5mrnLziXbnMX7nZjdX4XinEWaW3nImgbPnpWMXZWsWNG2XAWOXZaJ7VWHLCzMnlab7mKTHF6dXl7KXQmXnvXkWJW-WGXHG4mJn6naSw3Zqz6zy1Xp7wHNX+X1bk2hXU2RXdbtn+ryn6Xhrc2jn82FWbXznCGuXhG2nRGXblmyWHmKW9WqX03DXaWs2STA6RanGO2JLFX+H8X5ruX+3eXB3SXtXumU2x202vXJ2fW6WTWpWC7TbmW5XsXEmzm8W7WCWHWkrmqSWXXh23Xd2PX9WJ2xWp3jXJX-Wz2OHjGD6Q3r3cWx7OX7W12FmnXsmgO3q8mR3gm62caG3GG+LAaZ2v7UnxmJrJmAWjztGIP72oOiWn3nWg3XWwza29362tm0O9KMO8LZ22iLWF2R6COgWI2QW+3oOyPYOE3cmqHyWkOaOUO6PGt0OvyibmP2zWPcOC2syKLOOq76rQGeWbn+PG74OhPEP3WinP2D3v2j3p2mOsOxn535PO2AHb2e3IOePSPnaWqt3q2d3qOP3x3DO9bjPf3s3W3sOLPzKrXeHrPwOuPe21P12NO56BPtP2rhO9PuqdbxOPzu6T3-3GWcPAu8PC2OPw2VPz6y3L6B2nOX3t34v339OPPerD3M2fPMPlHzO83LPF2u2bPmm7OIvePHPn2KPX2qO5zROkuGGJOGOpPDqzO52musuFPJKYbbbBHXDCuwXiueuL3KG4vdOKvEvNnhuUvdm0uc3-OpuIagvTmwPCOwuOvvH1OYPoutPoXeTD0EvsahufajXGPpOJuWOg3LXsvFPrLlXgGhHOuHOsm7uoX1uYWnutuXudu3uf2PvxuGvJv23mv2OlO8uS2Y7rvIvbv437vIfHvq0RP3P93qujPavEeA6vvZOfu2PNHcvi2VXgeceuuwf8eIfKPYXCntv6H4fvOqe87kfvu1vfuZul3bXbPiP7PHW+PweKGufoe3PKuyfRWvPKexvqfhfafRf6fQ3GfYbPGWelubu5eOeFe+vuesbvq4fO6NfCakeHGjvUfpurPpm2uiPV2ZfH3uvyO1vFfifnube+e7emHBf0HRmUe5PXeWuQuLv8vS3o31WK2Omq3THyvlfefcrX6w-NehenfGuXeTu-vZulWPHI3jek-y3fGIX-Hgz0-NvM-YeQ+c-JOHeteC+o+6e0eGeMemegfFuq+iuN2SveuyvG+BvSfaPdudnm2Du-PC-o-i-xfWvQuE-seTfcezejGYuHuMqlfJ+Vfp-+f7fBrHfI+Re4PL2QPrW4-lOsfJ7N+2e42d+CeA-ni4Wj+xOZ+m33n5-hbL+u-YNrg31599DeFfQfuk2r7gs+WQ7cfm+yb7B9s+pTU-obQj4xNA2uvHvqAIB7l9uOIPWXr7006c9LeB-TalP2-4n9c+7ffPhfx15X9gBrLUDuy374LdycT-UHi-0hYW94B-XcgV-1e6h82+Z-DvnQNBrd8Y+6PXASu2rokdCB7PV-iQN4FW9aGGzFvigOoEiDaBGA81hIOX5u8b2a-B-lGygHD8ou5vAJsoLIGf8s+a9DQcILQEjMdBJlLAZIN77SC72XvAgT7wUHcDLBLnDPof1sH9MaumgxwaawDa6DXB+g2Pu7yMHM9IBq+Z-hAz8H18k2rnIIc32QFIswhwzCIQB1UYMCxeBg87vfwSHsCh+y3EfqtwYHv9OqqgjOgawp65DUW6XNtkvz+and8OYA+bkb0SEKF5BXAuvlOQCET9+BwQpoerxaEtsAB9AoAcUNiGGD4+xgyvqYKqHmDFBPA0YQgMyFIC7BOQhwXkNPYZcAuMQqQXN0B5sC0mSQzgSkOGHlkrBgfGHnsJCHNDDhrQw7ovz0GdCS+Evbtu12l7eDHqvg+4WrQb47DxhWQ-YRm2mH-8ZO4g6IT8JX539Me5Q64QMJ8FDCtW2wvgTYKhGvCph7wmYfCJlaIj5Wiw0oaiIH4VC1hpvIgfL38HgjcRPPfEZMMba+05+f7T4V3zJFXtb+cQ5YWiMJaDC7h2IpkSoPWaNCv2hI0bjQPQEHMohRQvXswKLbgD8BrPW4ZWzgE4iJRTzT1uTxlEA08+8os1i4KVHYCVRBvXoRAJpE3CRRWo5zuKOsEsiXhbI+jkaLlFOCFRZo+YcqP5FLCyh1I9EY5WBFYi0+6QwIZCNdHSj2R73Y0V6NNGF1eRN-YLgKMDFXDhRmI0UeGIQ4Qi8R0YzzrGIR7xj8hJw47kiJKEsC1R4XDUfaNT7ainRTwxAXQ2yEwiiRcImngiPNFuCcBFwvATWI4F1ja+YoiMWMPzEtjoRoQ9sVyIX48juxZw9wX2JkGqdaxWYh0aVx1HOjreE4gkUWIF4ljjh7Q74eSPOFl9lxBXSoXSJBEjjcxzI7cWoNbFTjZRWgk0ZEJ9EE8Fhp45dp4NkHe9Qx2YhsaOLzEuidxbokbh6JfEJi3xSY+cRWIpFVjrR6owcWuPrGOigJd4hoQiwNF7jUBRwtoc7w6EnjFxZ4n8SuOQn-j1xY-TcU2N2GgSYx7ogmpBNLFHjkxIAy0T0MuF9DbRGIiiahI3GNiP+IEh8ZOLeHPjwhh4giceL5GpiAxVIjMQ+14nDicxOnYCfeKlGFiGJqXGcbMK7G+iLR-oykawK4nBiY2GrPiVRIEn1DJRWEtXjhNhHaSSRmA2CURN7EkSpeXg1cYpNgFoTbxuoixgZ2wmaT9uDkzsaSOcnSSzuCEziTaJMnJ8a+3k-iehL8nCtKBQgsSXhO5GACPxfomSYZOrFXdyJsbACT5JUkYTrJ+o2yUFM5G+cdJYUvST2PYkeD3Jv4oEUVMon+9SBNEqMXRI0ngTGJ4k-CV8NYlMCDJUU-sQVMvFb96RrsbgBABgAIAUA1AbAPgEIAkByAlAagGtIYDMA2AnAWaTeNKnJTkOgg1vulI+GzispEPT8cRO-HNSyJk05Ie1NqGdTBJakmyahz6laSapjkxUfVIXGuTbpAIjyYVLMlKTAJvkrcZhIqkfS9u1U+rp30ukUNrpAMyXkDJameS2p5kjqY8NelQyAplUz6cFO+mhSnJf0uCV+NRme90ZIMlPmDJKkbdVJeMqrgTNhl-8Qp2vXSdlP0m5Sxp54xPrSKmnXjlJDMsqXqPxkwzZ+bM4mRzLqlcyGpo01UYhIHEPTNRWM56TjKslizmZEs3-r63hliDZZV0nKZFMVnRSkJKsocQlIslJTIZ5U8Wcl0ll6zTOMs0mXLP+mNSlxpEi8QLMelqygBdQgpm9OhkOzdZx7dmQjLmFuzyZN0ymZd0BEYzQZVs7GdRNxl2ztZIcjkVLP1nOCYJZMlyR7Lcloz7pPs1WXTMSkQyup444SbuKqlZznZEczmUbO5kmyrRZs5WSXMtmbty5h022VrNV46zM5Tsz7i7N+lRz85Cs1ueNPjk0z4pXc62RXNTl9zj+aUiCQNMymRym58snmabKnnAyLZKEsufPJ7mVyhJ6kwKYTLhn1yDZrszee7InkcTd51M-eV5LnnJzLJgcpmf3IzlxjPRzEyScNL-r3ympRc72XaIPlJz1ZKczWf5PTk-9B5Yc6WQ3MNlIzjZ3Q4BVTOLlgKX5o-N+TbJPlBz7ZcCn+UxIklDTwpKYluQ-L5kb9n5mMw+bgoXnQKUpJ0+wWdOJEkzR5t86OSjP+EYLQFPEuhRAv9kvSmFx023qdNXkZSLpG8lBc3LQWey7p-CkMYItfmQL35jzGBV-KIXFjf5pCucXnIinyLC5fC-mVgpUU4K1FeCxeZouXkSL+pUi2qTfNkVbzKF6CuOXvI7ngLVFwijWR-LTlaKqB04xBdfM4XOK7528yedQsf60LE53it-iIr8VLzUpdir6dnO9G5yx5hinLlQq9mmKBFsSixT4qgWJKbFyS1hZIvOmOLQlDeZGQXMBkmKaFni7BTUKKXqLR2FAlhQcLYUdiR574rhePIiU5LFFeS5RQUpaXxLfFGi5heIvKX2LKlP0vpWEu4V1LY56-aJU0vMXjKlBxSqZWIvUFdKKl7C3pRkv6VZL-uCikBSMtMm0yhFEynZe0oEEzKDlcyo5UgqcU1LUF2StxWspMFmKxlfvSxYwpKXTL9lbY7peHJCWLKPlcir5RcoaXrK-lNyuJdsraUk9HloKp8Ycp6VvLqlcWWpUArhXuKn5Gy-5cQK2Goqg+PU8+azKHnn8c557chWxIJXGKiVmC-JUisKV3KKVzwqlSzMdkIK0liYhlQYooVGL6lrKpRdctnmcqUVVi0RYNyeVgqsVEK+lYBxFVMrBl3ylYf0NGUcqtl5KuVcCr2WPjRJyq4JaqsKHqqRpmqwlT8tWGIrpV+qxkYat2UKqMVpql5dishUnKllAy1xbau1XcTdVjqgFa0pdUPKJh9Ei+XXOHk4qoVeKz5ecpZV2qdVUqmAcioNVArXVHSxVZis9Uqr0lwqzJaKthXJrA1sU6ASt1DVcrw1aKyNb1JpUCqr5FqployutX+qy1QohSZsurWyqs1Ea1kVGsbUmdY13qotacpLVJrxVKaoNWmqrVkrnV-autYOobX8qR1dKwtWquLUaqO1068tZmOaW9rM1x86xSCpNWGj815qzdZau3XtqxVqy-dd2tJUMi0hS6yldXLAnDq6uza69a2qtWAKbVnaoMQep7ULrX1J6+VTmvdUXrUlP6oVVuonU7r71vCiVVcrinpqZVx6kWUdLdXnq7JQSwVdBPHW+qzlpfPdV2rkFeLMNi6iDUatw0iSYNRMwjQUL-W3qANu6h9RRr-GgaX1Iw7lc2I-VDq11360dS2sy7hKONKGmdRWrMF49NhNG7Db3NKWdKlVl65jWWKL7LLmV5G4DU+r1VHqFNUPfBZ-NsWzLYNom39eJq02AadN8kyjYerA18ba176s+XytDnrrRBYm04dZsk0e9UNjSh1RhqdXgbFNxm-xaZueXmaN18Gm9YhrvWlrbNxkkDc+osEhajNp641Qxvw3gqr1MW1jXFvY3Ia-N0m5Lfpsc0PD7ly6gsdSuE3h8oJLGqzX6qK3xDdN9mnjalqc1vqeVgm1de5pE3RaiNCGkjZOrI2cbWt3GlLfJrS1E8Mt9GmudGtpWebLN3mprQlrG12aJtZW3jRVv420SetNWvrXVr-lkL-1LjFZVJsfVtbJtqQzrbRuzXoq8NtcxbdoOW3ljVtU69bUlr00hrytYI5zd1tc0DziFa86RY3OG1Ia1tF2rja1Ou2gjoGd2gddVrc3wKPNL2vLY1tI1-Ditl2zbT9u21-autAmwHd-J0UkLBp+itjWdu02faYppWvHR1p23-aid70knfuN0Xk7EZ0Klxc1sFHjaYdW2hnQToR1VbeVQO0nSDqqXxrdyMKj7VDr50JyBdU227aFtm1QbHtC2ptRZvR0rbMdq-XnRtv5306ldjOwnXtuJ3aK2dZO9eWDq50Saed6Yr7VdsV03aTdwulzSzot24T5lHCqXeFR83265Jju3HUFoM3Tb9+YWpJSprzVRalt2ut7brpRFGTad32kPb9vh0q7IND2rLU9s10DaGtOukbVjpa0G6FdRul3ULoz10a1d2ejXajtfH5749hevXQ7uT1O6y9cOu+kzrN0e7AlOW9TSxLbWFbId2O6HaXtT347096WzPfWoO0o7+tsewbbFvB3xbZdI++XTPPH2C7J9M26fSutn3A6HFCyn1bbv93D7i9Qew3ZvuN0V6p9VerPfNq-VHa9FnOhNTLtG1y6S9G++dRPs72m7up+25HQfu93HLiNJ+97e-rX2f6YlzujvYmz-1Vzzdves1f3v-mD6qdNmmnebJJUwGDple+7TPsAPi7D9Pu4-a-u51n79dF+sfd-q32-63dAOnvSvLU1wbF9+W5fUPtX3n7W9wemg9fu33h7Vd9+z9bVoPEc6ZFYBhPWmMD3cHL9vB8vfwY+ru7g5nu+ybltYMY6m9ie-KdPOgPt7cDt+-A3vsIOW6JdR+0A2Qbt0UGW9WBwLXIdgOCc8DiO0Xazq92vKx1Q2iQ5oakNJ6bD7KvQ8LIMNOGADYukw8QZAMeGLDp+zg5QZkPUHqhoe5XYEZF3BGXDqhlAydsp0JNqdH+qg1-viNp66Djh5I4gaYMx60d6hgvRDuiPWH25th-Iz-rgP0HmdyhpA8wa10VHG9VRiA1wd8PBqr98hwo0kaUOELWjZR+vRpsImSHZJPh2o34f6P2HYuQxhgy0dKNMaWDDezTeAaL0xHejc6+o7QcaNFHhjsC0Y2sfaMbHJjXh6Y9oY8V1GNhAxw40seaMjHVjl884xMaklXG8pSsiadgf8Pgymj3elYykrON56PjAC9A75p6OzG+jdh-Qzvrv0EGQjrhr1V5s6Mr7ujOxmE3sfuMLG9+ih5Yy8ZBNvGwTA+07VkYwM5HYjeR3E-CYEO76kdyJtI+sfBNoGKTUJrE78buNyaHjDhp40CaJNmbQTC+i458a6PbGajXJuY3CYCMInDDjJ1IwRpZNknMj-zKw9Id2PoaZTAJo44SZOOvGY1pJ1A+SbVPVGNT2JrU-sb4ODG5TQRko8ScNMinWTJproeqZmNSnYTVp3k4sdtPFHGDDp57eMZVMFbITAe90zob+PzG6TBJ54-qYDO56nTwZ9g6GbdM3HiV3J7ft6fxMt09TASg04Gfq3OnVTrps0+GduPSmvTeJwnvScRNGGmTSp940mc8Pinm95pj0ziZ5NVmA58p5wyoYbNGmMjIZ9k2GbTNsrPTtJ2UzWZ7MpG+zfe5U8aeLO-DWzZZ9MxWYnM6n+T-++00KZJOJmFzQ5005iclMRmMz006048d9PHG8z8ZuvYWabORGtjy50c5KstPrn6Zm5hA-6Z3OOnyjopiE8OdTM-GTza5zs9GZzOxnrz35gs8dop0HmSzR5ts8BfHOgXJzMZgU3GagsJnfzRZuC0ua0NAXyzyFzM12YSXTntzkW4U9hfvPS7yDpZ582hsrWVmwLgrdC5BYou7mqL+55MwBbosEXVzRFs81merNoWtzX59iz+aDNcXmzGJiU4hcIsdniLzFmtqxYi2qaxjd5qSw+amPfG257Z18yhY3OXnczql6PZRckuDnuLh52SyubHMKXBLJFyZXabEtqWzLGliy9JY4MIWbLL5xi2+e7m6mILJlj1epZgsv6aLlh3i7paQt2WhZhlqc05eBOYXbzoV8Q1pa+O8zclAWkC4pdQvgWVLZS8S9Bef2pXwrURry-RaysCXYr75oy4FYKsuWOL5l2C5ZfgvWWKrCK7K-ZaUsZDRLiVwq1haathWc8rAUsAACYAADJNaAA) 🙌

I just merged a PR that switches it, and it was fully backwards compatible so previously shared links won't be broken either.

Great idea!

**Comment by breck7** [comment]
Share successful 🚀🚀🚀

<img width="650" alt="Screen Shot 2021-04-13 at 5 29 19 AM" src="https://user-images.githubusercontent.com/74692/114579133-44f5b180-9c19-11eb-81f5-1c5593cec82b.png">
