### ISSUE TITLE
Feature: Comments

### ISSUE THREAD

**Issue by danielsnider** [tone-row/flowchart-fun#11]
Be able to comment out a single line or block. 

Examples
```
// Production
User
  Load Balancer
    Webserver
      Database

"""
Development Environment
"""
User
  Webserver
    Database
```

For me this would be useful for noting down extra details that come up during collabourative brainstorming sessions. 

A future idea would be to optionally render the comment text in the SVG nearby the child node.

PS: Great tool!

**Comment by rob-gordon** [comment]
@danielsnider Thanks for making this issue! I bet a lot of people would find the ability to make comments helpful.  I'm migrating all issues related to syntax-changes over to discussions so people can share their thoughts.

(For other people) Please 👍  the original post if you're also looking for this feature. It will help me prioritize! 🙏
