### ISSUE TITLE
Add a "Reset" / "Clear Chart" button

### ISSUE THREAD

**Issue by physics515** [tone-row/flowchart-fun#124]
It would be helpful to have a reset button that would reset the chart to the default "fresh" chart with the syntax examples. The first thing I did was remove some of the examples while playing around before realizing that I couldn't find out how to do more stuff without finding the github page.

**Comment by rob-gordon** [comment]
I didn't want to run the risk of erasing peoples charts, so I opted to just re-add the help syntax for people trying to recover.

I fear this button may be hard to find though. If you have suggestions for making it more clear, let me know!

https://user-images.githubusercontent.com/159949/118023106-2293a880-b32b-11eb-9008-cc1fc8b996bf.mov

**Comment by rob-gordon** [comment]
@physics515 Going to close this, but if you feel like there's another issue not being addressed by the help button feel free to open another issue.
