### ISSUE TITLE
Adding an order of next branch

### ISSUE THREAD

**Issue by beejei** [tone-row/flowchart-fun#125]
Hi,

I'm really a big fan of this neat and fancy tool.

What would be great for me is, having a order on next branch.
Let say I have entered data below with dagre layout:

`
first
  1. Second 1
  2. Second 2
  3. Second 3
`

Expected:
I'd like to see the Seconds in order of its number
e.g.)
first
  1. Second 1
  2. Second 2
  3. Second 3

Actual behavior:
Actually the order is random, I cannot control their order
e.g.)
first
  1. Second 3
  2. Second 1
  3. Second 2

Thanks, appreciate for all of your job

**Comment by rob-gordon** [comment]
#144  helps ensure that nodes are ordered according to their line order.

Can you let me know if you are still having trouble with ordering?

**Comment by rob-gordon** [comment]
(Also sorry for the delayed reply! And thank you for opening an issue!)
