### ISSUE TITLE
More than 2k people saw my tweet today

### ISSUE THREAD

**Issue by beejei** [tone-row/flowchart-fun#157]
I just want to say many people saw [my tweet](https://twitter.com/beejei/status/1430444206749745154) and reacted, tried flowchart.fun
I personally think this is the super great way to spread a genius idea as a tool over the world
Now I'll try to introduce by setting up an internal instance within our company and colleague to use it for organizing their ideas (especially process relevant things)

Super thanks!
Please feel free to close this issue immediately

**Comment by rob-gordon** [comment]
@beejei That's amazing! Thank you for sharing it and for your donation! If you have any trouble setting up an internal instance just let me know. Happy to help!
