### ISSUE TITLE
Bug?: Downloading SVG reflows the graph

### ISSUE THREAD

**Issue by jjkinsey** [tone-row/flowchart-fun#18]
Repro: Create a simple graph, drag a node to a new position, and download the SVG. The node will return to its original position.
Expected: No change to the graph from downloading the SVG.

My "workflow" (if you can really call it that) with this app so far has been 
  1. write out the graph description -> 2. drag boxes around so that everything looks nice -> 3. download an SVG.

It makes sense to me that adding new text reflows the graph, no obvious solution to that problem, but it would be nice if downloading an SVG didn't reset everything.

Only kind of related, but I've noticed sometimes the download SVG button disappears and necessitates a page refresh to get it back. I'm not really sure what that's about. If I can figure out how to reproduce it reliably I'll open an issue.

**Comment by rob-gordon** [comment]
@jjkinsey Could you confirm that the deploy preview from #19 fixes your problem?

https://deploy-preview-19--agitated-knuth-acd401.netlify.app/

**Comment by jjkinsey** [comment]
Yep, looks good.
