### ISSUE TITLE
Bug: After Downloading SVG, social buttons and 'Download SVG' buttons disappear 

### ISSUE THREAD

**Issue by MADanson** [tone-row/flowchart-fun#20]
After downloading SVG social and 'Download SVG' buttons disappear until reload of page or resizing of window.

Reproduced on Chrome and Edge.

Cheers!

**Comment by rob-gordon** [comment]
@MADanson Which OS/browser are you using?

**Comment by MADanson** [comment]
- Windows 10 all up to date
- Chrome
- Also tested on Edge

**Comment by rob-gordon** [comment]
@MADanson I fixed an issue with resizing this morning (#25) that I believe is related. However, I do see that on Windows, the download bar covers part of the vertical space of the screen.

![Screen Shot 2021-03-03 at 11 55 38 AM](https://user-images.githubusercontent.com/159949/109842434-15b25480-7c18-11eb-85a7-7ec236359a9a.png)

Let me know if this resolves (at least partially) your issue. 

If not, more info or a screenshot would be helpful.

**Comment by MADanson** [comment]
Resolved! Thanks for your help!
