### ISSUE TITLE
Self-building

### ISSUE THREAD

**Issue by GreenHatHG** [tone-row/flowchart-fun#22]
Can I build it by myself
Can you provide tutorials or Dockerfile?

**Comment by rob-gordon** [comment]
@GreenHatHG You can absolutely build locally. I've added the basic steps to the README [here](https://github.com/tone-row/flowchart-fun#how-to-run-locally). I also added a link  to the create-react-app README, which has more comprehensive instructions.

If you specifically need a dockerized version there are a lot of resources for dockerizing a create-react-app, for instance https://mherman.org/blog/dockerizing-a-react-app/

I hope that helps. If you have trouble feel free to open another issue.

Cheers!
