### ISSUE TITLE
[Suggestion] Chinese translation of interface

### ISSUE THREAD

**Issue by cztuc** [tone-row/flowchart-fun#230]
Hi there,

Thanks very much for making such a great tool.

I just want to raise a few tiny issues with the current Chinese translation of the interface, and have listed them in the following table:

| English  | Current Chinese | Suggested Chinese | Reason |
| ------------- | ------------- |------------- |----------|
| Dark  | 黑暗  |深色 | 黑暗 is a quite formal translation of being black, which is different from being dark; In the context of UI, it's common to translate "Dark" to "深色" as in [OSX](https://support.apple.com/zh-cn/HT208976) and [Windows](https://support.microsoft.com/zh-cn/windows/%E6%9B%B4%E6%94%B9%E9%A2%9C%E8%89%B2windows-d26ef4d6-819a-581c-1581-493cfcc005fe#:).|
| Dark Mode | 黑暗模式 | 深色模式 | Same reason as above. |
| Light | 灯光 | 浅色 | "灯" means lamp and "光" means (visible) light, so "灯光"= light of a lamp. The common translation is "浅色" as in [OSX](https://support.apple.com/zh-cn/HT208976) and [Windows](https://support.microsoft.com/zh-cn/windows/%E6%9B%B4%E6%94%B9%E9%A2%9C%E8%89%B2windows-d26ef4d6-819a-581c-1581-493cfcc005fe#:). |
| Light Mode | 灯光模式 | 浅色模式 | Same reason as above. |
| Expand  | 扩大  | 放大 | There is a subtle difference between "扩大" and "放大", but "放大" is the correct one. |
| Contract  | 收缩  | 缩小 | Same reason as above. |

I've made corrections accordingly in this `messages.po`, in case it will be of any use: 
[messages.po.txt](https://github.com/tone-row/flowchart-fun/files/7775235/messages.po.txt)

**Comment by rob-gordon** [comment]
@cztuc This is amazing and very helpful. Thank you! 🙏🏻 I will make these changes in the next round of updates.

**Comment by rob-gordon** [comment]
@cztuc Sorry for the delay. These improvements are on https://flowchart.fun now. Thank you again for the suggestions!
