### ISSUE TITLE
Text overflows diamond shapes

### ISSUE THREAD

**Issue by mrmanc** [tone-row/flowchart-fun#231]
Creating a lot of text in a diamond shape causes it to overflow (appear outside the sloped lines of the shape), due to the rectangular nature of the text box. I know this isn’t a trivial problem, but I wanted to make sure you were aware! 😃 

Lovely product, although I find the syntactic indentation a little hard to manage with a large diagram. Definitely going to recommend it to people.

**Comment by rob-gordon** [comment]
Thanks for opening an issue! I've seen this behavior on stars behavior on stars, so it figures it occurs with all the non-rectangular shapes. I'll look into a fix! 🕵️

---

> I find the syntactic indentation a little hard to manage with a large diagram

If you have any suggestions, I'm all ears!

**Comment by rob-gordon** [comment]
> I know that would make it more verbose for simple diagrams though, so it’s a trade off.

True! And it's definitely still possible to declare nodes at the same level, if you find that more readable. 
ex: https://flowchart.fun/c#IYKABGAUBGCU5QMb2gyx4RvRaNriA

**Comment by rob-gordon** [comment]
Hey @mrmanc ! Merged a bit of shape resizing last week so you'll get better results with text in other shapes now. Going to close this but open up another issue if you have any trouble using it.

Thanks!

**Comment by mrmanc** [comment]
Awesome, thanks so much! 😃 
<img width="357" alt="image" src="https://user-images.githubusercontent.com/547606/160282923-698cb1d4-3bfb-4d70-9f1d-8eddac35d505.png">
