### ISSUE TITLE
Fonts for SVG downloads

### ISSUE THREAD

**Issue by physics515** [tone-row/flowchart-fun#234]
So, I think this is a simple request. Sorry for the brevity but, could you provide a list of resources, when exporting an SVG, that I would need to make it look the same on my local PC as it does in the editor?

Specifically, fonts. Maybe a link to the Google Fonts page (or whatever you are using) for the fonts used in each theme. 

When I download the SVG it just displays the default font and looks quite odd and causes the text to expand out of the boxes in some areas.

Thank you for this extremely helpful app!

**Comment by rob-gordon** [comment]
Absolutely! You can download all the fonts used from here: https://github.com/tone-row/flowchart-fun/tree/main/app/public/fonts

I'll look into what I can do so that the fonts are embedded by default. I'm not sure what's possible in SVG of the top of my head, but I'm sure I'm not the first person with this problem.

**Comment by physics515** [comment]
Just to give a bit more info, I am wanting to edit in Adobe Illustrator. So embedded fonts will not necessarily help me anyway. 

I can grab the fonts now but, as you might add more themes in the future it might come up again that someone else needs to download them.

**Comment by rob-gordon** [comment]
Ah okay, yeah that context is helpful. I'll think about ways to make it more obvious for people in the future wanting to do the same thing. Thanks!

**Comment by physics515** [comment]
I tried grabbing the fonts last night, the problem I'm running into is the `.woff2` fonts can't be installed on windows, I tried `cloudconvert.com` to convert them to TrueType fonts but the conversion was not successful. A quick google search didn't turn up `.ttf` versions of most of them either.

Again, it's not a huge issue as I can change the fonts later in Illustrator, but it would be nice to have it appear correctly on the first go for large files, or when opened in chrome.

**Comment by rob-gordon** [comment]
@physics515 I didn't have any problem converting the Virgil woff2 (-you may not be referring to Virgil, in which case, let me know-) on CloudConvert. However, when I installed the font (I'm on mac, worth noting), the embedded name of the font was actually `Virgil 3 YOFF` – so all the font strings in the SVG, which are just `Virgil`, weren't working. I did a quick Replace All of the strings and then it was looking fine in the browser.

This is by no means a good solution, but it may help in the short term. If you're not working with Virgil, or you're unable to install the ttf on windows let me know. I'm less experienced with windows but I have a mac with bootcamp so I can give a try if needed.

[Here is the ttf in case it helps](https://file.io/S7DWTRbqfVHs)

![Screen Shot 2022-02-04 at 11 01 35 AM](https://user-images.githubusercontent.com/159949/152561463-95e36e59-0d2e-418b-9097-000dc9f18ceb.png)

**Comment by physics515** [comment]
Wired! I'll give it another shot later, cloud convert told me that it failed to convert the file. Maybe it was a corrupt download, or something.
