### ISSUE TITLE
Sessions keep expiring on sponsored account

### ISSUE THREAD

**Issue by mtlynch** [tone-row/flowchart-fun#246]
How long do sessions last? I signed up as a sponsor yesterday, and twice already, I've returned to the flowchart.fun website and found that my session is expired and I have to log in again.

Could the session expiration be longer, like 30 days or never?

**Comment by rob-gordon** [comment]
Sessions were set to 1 hour- which I agree is too short. 

We're using @supabase for auth and the maximum length for expiry is 1 week so I've bumped it up to that. I hope that improves your experience!

**Comment by mtlynch** [comment]
@rob-gordon - Thanks!
