### ISSUE TITLE
Allow for multiple lines from the same source / destination

### ISSUE THREAD

**Issue by james-powis** [tone-row/flowchart-fun#30]
Currently the lines are drawing over the top of each other:

Ideally these lines should be gapped or curved (such as when you have opposite source and destinations.)

<img width="1251" alt="Screen Shot 2021-03-03 at 12 11 39 PM" src="https://user-images.githubusercontent.com/2318207/109858928-a473a100-7c19-11eb-9dac-e536ba9c3ab4.png">

**Comment by rob-gordon** [comment]
![Screen Shot 2021-03-04 at 9 20 44 AM](https://user-images.githubusercontent.com/159949/109977570-f1fc1680-7cca-11eb-8d7a-36cd1680c1f1.png)
