### ISSUE TITLE
Do not render blank lines(shapes)

### ISSUE THREAD

**Issue by james-powis** [tone-row/flowchart-fun#31]
Blank lines should be ignored, or toggle-able to suppress.

 In general blank lines help create organization which helps the user, having extra objects created because of a blank line in the left hand text area is not very user friendly.
 
 Additionally comments should be ignored?
 
<img width="1089" alt="Screen Shot 2021-03-03 at 12 14 19 PM" src="https://user-images.githubusercontent.com/2318207/109859310-0af8bf00-7c1a-11eb-99af-74986f44565a.png">

**Comment by rob-gordon** [comment]
Totally agree! I'll try to get a PR in for this later today.
