### ISSUE TITLE
[ENH] Add left rhomboid

### ISSUE THREAD

**Issue by 0dminnimda** [tone-row/flowchart-fun#348]
Mermaid have not only rhomboid `a[\"blah"\]` but the left version `b[/"blah"/]` (which is more commonly used to represent io operations)
```mermaid
flowchart
	a[\"blah"\]
	b[/"blah"/]
```
From what I understand it should relatively easy to add this
If maintainers don't have time for this, I can make a PR

**Comment by rob-gordon** [comment]
This app uses [cytoscape-js](https://github.com/cytoscape/cytoscape.js/) which only supports the shapes listed here (the same ones currently available).

I can look into how easy this will be with the custom [shape-polygon-points](https://js.cytoscape.org/#style/node-body) option.

**Comment by somaniv** [comment]
This is a good idea.
I've created an issue on [cytoscape-js issue](https://github.com/cytoscape/cytoscape.js/issues/3123) and the associated PR with the new shape: [right-rhomboid](https://github.com/cytoscape/cytoscape.js/pull/3124)

**Comment by rob-gordon** [comment]
@somaniv That's awesome! As soon as https://github.com/cytoscape/cytoscape.js/pull/3124 merges I will update Flowchart Fun to the latest version of cytoscape 👍🏻

**Comment by rob-gordon** [comment]
@0dminnimda Left rhomboid is available now!
