### ISSUE TITLE
Editor spellcheck

### ISSUE THREAD

**Issue by RickStanley** [tone-row/flowchart-fun#359]
It would be great if it was possible to have the system's (or browser's) native spellcheck enabled in the editor, by right clicking it and enabling the according languages.

Like in Firefox:
![grafik](https://user-images.githubusercontent.com/23178554/201545892-486fdf69-02cd-4ef6-8d62-ab8534e763fd.png)

or Vivaldi's:
![grafik](https://user-images.githubusercontent.com/23178554/201545915-ec2e5967-e862-4874-99b7-4c27f3b38c86.png)

And so on...

It would also mean to enable the context menu on the editor itself, right now you can't right-click to see the navigator's menu; I would suggest giving it the behaviour like YouTube (the first one that comes to my mind) where one can right click a second time on the video and if YouTube's menu is already open it shows the navigator's context menu as usual.

**Comment by RickStanley** [comment]
Oh, I see. Seems to be an upstream issue/feature, should I close this one?

**Comment by rob-gordon** [comment]
Sure. Sorry we can't support it yet!

**Comment by RickStanley** [comment]
No problem! For some reason, I was sure flowchart was using [Codemirror](https://codemirror.net/) behind the scenes, it doesn't have the right-click "problem". Thanks anyway!
