### ISSUE TITLE
Input Chinese without line break

### ISSUE THREAD

**Issue by tangwanchao** [tone-row/flowchart-fun#36]
<img width="1774" alt="截屏2021-03-0413 46 46" src="https://user-images.githubusercontent.com/34504415/109917324-13232e00-7cf0-11eb-8296-3540e27adbcb.png">

**Comment by rob-gordon** [comment]
I want to understand this problem better. 
Would you like the boxes to expand to keep longer lines inside the boxes?
<img width="144" alt="Screen Shot 2021-03-04 at 10 13 05 AM" src="https://user-images.githubusercontent.com/159949/109984896-36d77b80-7cd2-11eb-9369-70c1617ffd3d.png">

Or prevent lines from breaking when there is a space?
<img width="119" alt="Screen Shot 2021-03-04 at 10 13 30 AM" src="https://user-images.githubusercontent.com/159949/109984967-46ef5b00-7cd2-11eb-9655-04cdcb528991.png">

Or both?

**Comment by akinlong** [comment]
Keeping all the lines inside the box will be a good option.

**Comment by tangwanchao** [comment]
Keeping all the lines inside the box

**Comment by JasonkayZK** [comment]
Use specific space between chinese word can create a new line, like this:

![flowchart_demo](https://user-images.githubusercontent.com/40811521/110207553-3223ea80-7ebf-11eb-8b54-990b7a3684a0.png)

The chinese version instruction "source code" is below:

```
这个应用 使用纯文本构建
 新的一行 创建新的节点
  文本之间的 空格可以提供换行
  缩进创建(临近节点) 的新的子节点 
  并且任意文本: 在[冒号+空格]之前， 创建一个标签
 [linking] 你可以使用小括号 包裹的节点的 ID连接节点
  比如: (1)
  每一行默认的ID 就是他们的行数
   不过你也可以 使用中括号 定义一个自定义的ID
    比如: (linking) 

// 单行注释

/*
多行注释

Have fun! 🎉
*/
```
