### ISSUE TITLE
Add Dual Window/Monitor Support

### ISSUE THREAD

**Issue by physics515** [tone-row/flowchart-fun#369]
I want to start by saying that I have no idea the technical issues surrounding this however, I think it would be useful for Dual Monitor workflows if you could have the "text pane" and the "chart pane" in two separate windows. 

I am currently using an ultrawide monitor and when working with deeply nested charts it is still a bit cumbersome to use because of the constant horizontal scrolling.

If i could have text on one monitor and the chart in the other it would make things much easier. This text in one window:

![image](https://user-images.githubusercontent.com/7359379/203163613-0cd58184-c079-402a-9323-3cbce1d13a78.png)

This chart in the other:
![image](https://user-images.githubusercontent.com/7359379/203163782-b39ff45d-901e-4f62-a285-083300c0fccd.png)

**Comment by rob-gordon** [comment]
Based on my quick test– this works with local charts already if you have two browser windows pointed to the same local chart. 

Making this work with hosted charts is significantly more complicated and I'll probably hold off on adding this feature until I decide to build out some kind of multiplayer mode.

Will that work for your needs for now?


https://user-images.githubusercontent.com/159949/203403964-266a8c59-d8b3-4fb5-880b-cc00b952bf99.mov

**Comment by rob-gordon** [comment]
Closing for now. Let me know if this doesn't solve your problem.

**Comment by physics515** [comment]
Ahh.. I'm using hosted charts. Multiplayer mode may very well be what I'm looking for. I'm starting to get more people in my company using this and working together on charts. I think that would solve two problems. But I understand that would be a fairly massive undertaking haha

**Comment by rob-gordon** [comment]
@physics515 It definitely would be a big undertaking, but it helps me to know that's something your company would use. I'll keep it on my radar and hopefully it becomes possible sometime this year 👍🏻
