### ISSUE TITLE
Problems with edges and nodes after `()`. ID and "Backward-Pointers" use the same parenthesis syntax

### ISSUE THREAD

**Issue by rafo** [tone-row/flowchart-fun#389]
From your Documentation:

Using ID's

If your graph uses a lot of pointers, it can be time-consuming to change all your pointers if the text changes in one of your nodes. In this case, you can give your node an ID, and point to the ID instead. An id is declared at the beginning of the line between an opening [ and closing ], and it cannot contain periods. ID's should be unique.

```
[my-id] A long line with text that I will need to change often.
Node B
  (my-id)
Node C
  (my-id)
```

If you change that to:

```
[my-id] A long line with text that I will need to change often.
Node B
  (my-id)
    Node C
  (my-id)
```

I would expect `Node C` not to get the edge from `Node B`, but from `(my-id)`. It seems that the syntax `()` makes a problem for the parser because it is also used for **linking backwards** "pointers", right? Apparently, after an indentation after `()`, no node with an edge is created.

**Comment by rob-gordon** [comment]
@rafo You are totally right. This has been a source of confusion for many people in the past. I'm working on an [updated version of the language](https://github.com/tone-row/graph-selector) that corrects this, and I hope to have it in Flowchart Fun in a matter of weeks.

I'll leave this issue open until it's fixed.

**Comment by rob-gordon** [comment]
@rafo Going to close this because it's a feature of the [new syntax](https://graph-selector-syntax.tone-row.com/). Here's a working version of your example: https://flowchart.fun/n#IIAgNg9gdg5uCWUCmIDu8AuALEGkA8NcsBDIgSTXjDBGSQBNcIQBjU2FCAMzygDoQAYgC2ATwC08BgCgAchAYoAQjJAgAFKMnSAlGvUgFSkAGEDW8VIb6AvPfsyA3gYBEABxIAnAM5IvrgBcIK4wXiTuWBJ+YEisGBABMgC+Mg72QA

Cheers!
