### ISSUE TITLE
Nodes are not correctly split after a multiline comment

### ISSUE THREAD

**Issue by bartTC** [tone-row/flowchart-fun#39]
This text:

```
Test
 Test 2
  Test 3
 Test 4

/*
Multiline Comment
*/

Test
 Test 2
  Test 3
 Test 4
```

Will result in this graph:

![download](https://user-images.githubusercontent.com/1896/109956476-fbde4380-7ce3-11eb-891c-e57dd2bb7452.png)

**Comment by rob-gordon** [comment]
Thanks for finding this. Going to work on a fix right now.
