### ISSUE TITLE
Support inserting a box in the middle of existing flowchart

### ISSUE THREAD

**Issue by hryb-michal** [tone-row/flowchart-fun#42]
Currently if I wanted to insert a box in the middle, I would have to tediously insert a space in all subsequent rows. I believe it could be solved by allowing multiline selection or creating a functionality which would traverse all derived boxes and insert it automatically.
![image](https://user-images.githubusercontent.com/45271398/109979234-f6dabd80-7cfe-11eb-966d-9d60be3f8e50.png)

**Comment by rob-gordon** [comment]
Would this be solved if you had more code-editor-like functionality? (Like indenting multiple selected line, etc.)?

**Comment by hryb-michal** [comment]
It would make it easier, but also if I had a big chart and wanted to insert something at the very beginning, an option to automatically select all derived lines appears to be crucial - having to manually select almost all lines would be a nightmare

**Comment by rob-gordon** [comment]
Closing all issues related to browser-based code-editor. If you have any other thoughts please add them to the discussion https://github.com/tone-row/flowchart-fun/discussions/45
