### ISSUE TITLE
Provide a way to find the line related to a particular box

### ISSUE THREAD

**Issue by hryb-michal** [tone-row/flowchart-fun#43]
With greater amount of boxes in a chart, it gets harder to navigate through existing instructions and find the desired one. Displaying line ID somewhere in a box (maybe greyed text in a corner), or highlighting the proper line when a box is selected would be really useful.

**Comment by rob-gordon** [comment]
> highlighting the proper line when a box is selected would be really useful

That's a really cool idea! I will take a crack at this later today.

Thank you for the suggestion

**Comment by rob-gordon** [comment]
Merging a PR with a quick and dirty approach to this. I didn't want to put too much logic into it since it seems like we'll probably move from a textarea to a browser-based code editor soon. Thanks for the suggestion!
