### ISSUE TITLE
What happened to help?

### ISSUE THREAD

**Issue by mbierman** [tone-row/flowchart-fun#471]
There's no help link anymore. and the Discord link is broken.

**Comment by rob-gordon** [comment]
> There's no help link anymore. and the Discord link is broken. 

Sorry for the confusion. The help page was out of date (using the old syntax) - it's been replaced by the Syntax Reference available directly from the editor (as long as you're using the graph-selector syntax)

I just found out today that Discord links expire by default. There's a pull request open with a Discord link that won't expire. Let me grab it and post it here.

**Comment by rob-gordon** [comment]
@mbierman Working Discord link: https://discord.gg/wPASTQHQBf

Sorry for the confusion!

**Comment by mbierman** [comment]
Fabulous! Might be nice to put a help link back in the menu so it isn't easily missed. Thanks again.

**Comment by rob-gordon** [comment]
@afrancht Are you sure? https://discord.gg/wPASTQHQBf says it's set to never expire.

![Screen Shot 2023-03-08 at 1 45 06 PM](https://user-images.githubusercontent.com/159949/223806281-8278f78a-4a50-45f5-930f-374ca0ced2a6.png)

**Comment by rob-gordon** [comment]
Closing this! Feel free to open another PR if there are problems with discord link.
