### ISSUE TITLE
Different shapes

### ISSUE THREAD

**Issue by rubjo** [tone-row/flowchart-fun#56]
Very, very cool, thanks for making this!

Part of the appeal is its simplicity, of course, but: any plans to extend with a handful of different typical shapes (eg. oval, parallelogram, diamond)?

**Comment by rob-gordon** [comment]
Hey, I responded to this over in this discussion https://github.com/tone-row/flowchart-fun/discussions/29

I'm trying to keep things which will impact syntax/features over in discussions so I can gather as much input as possible. Thanks for your feedback!
