### ISSUE TITLE
Saving/exporting/importing/tabs/bookmarks?

### ISSUE THREAD

**Issue by VictorioBerra** [tone-row/flowchart-fun#57]
Some features that would be super useful:

- entire chart save in query string for easy bookmarking?
- allow exporting chart data for savings or later importing (json/csv/whatever)?
- Save chart data somewhere like localstorage and add tabs at the top to work on multiple charts at once?

**Comment by rob-gordon** [comment]
> entire chart save in query string for easy bookmarking?

This is the solution I've had my eye on for a while. Just haven't had time to implement. The others are cool ideas as well.

Thanks for the feedback!

**Comment by rob-gordon** [comment]
@dionsaputra Going to keep this Issue open because there is another feature I want to remember to add 👍

**Comment by dionsaputra** [comment]
@rob-gordon thankyou for merged my previous PR. I was realized that it does not necessary to save complex json from cytoscape to generate the graph back. The syntax in text-editor is sufficient to do it, I have open another PR (#61) to export & import using the text in editor

**Comment by rob-gordon** [comment]
@VictorioBerra wanted to mention you can now store separate charts at separate url's. See [this](https://twitter.com/row_tone/status/1369712546643664898) for an example.

I'm leaving this issue open because I plan on implementing the query string idea soon as well, although more for read-only sharing purposes.

**Comment by VictorioBerra** [comment]
@rob-gordon  thanks! How do I save my URL?

**Comment by rob-gordon** [comment]
> @rob-gordon  thanks! How do I save my URL?

I might add a small navigation to move between charts in the future but for now you'll need to bookmark it / remember it.

**Comment by VictorioBerra** [comment]
Ohh, I meant when you hit the page, does it generate a moniker style url? https://www.npmjs.com/package/moniker

In the twitter gif, it wasn't clear how the URL is created.

**Comment by rob-gordon** [comment]
Ah I see. Sorry it's not clear. You choose the url! (Just by typing it in)

**Comment by rob-gordon** [comment]
@VictorioBerra Added a small `Share` button as well which opens a link to a read-only version of the chart, stored in the url, like you mentioned.

I'm going to go ahead and close this issue. Thank you for all the suggestions!
