### ISSUE TITLE
Feature - add tags to nodes

### ISSUE THREAD

**Issue by ahmedahmedov** [tone-row/flowchart-fun#6]
Only linking via the line numbers is problematic, because one has to readjust all the numbers again if a line is added to the middle. If we have a tag for each node, then we can link by using these tags and that would eliminate the line number sliding problem

**Comment by ahmedahmedov** [comment]
sample:
`this app works by typing [node1]
 new lines create new nodes [node2]
  indentation creates child nodes
  any text: before a colon+space creates a label
   and: you can link to nodes with their line number in parentheses
    like this: [node1]`

**Comment by rob-gordon** [comment]
I really the implementation someone suggested in the hackernews comments.

```
   1. hello
   2.   [foo] This line is Foo
   3.   This line is Bar and connects to Foo
   4.     (foo)

**Comment by rob-gordon** [comment]
Going to hack at this this evening! Thank you for making the issue!

**Comment by ahmedahmedov** [comment]
Glad that it helped :) Good luck!
