### ISSUE TITLE
Artifacts after leaving the app open for long period

### ISSUE THREAD

**Issue by hryb-michal** [tone-row/flowchart-fun#70]
Is there a possibility that something on the app side is infinitely accumulating storage?
After leaving the tab with the app open for a while, I was surprised to see lots of artifacts on the graph.
Refreshing the page didn't work, copy-pasting code from the clear version didn't work either, I had to restart the browser, and it had finally helped.

![flowchart](https://user-images.githubusercontent.com/45271398/110258816-c5831b80-7fa4-11eb-8663-7f06dafa6914.png)

**Comment by rob-gordon** [comment]
> Is there a possibility that something on the app side is infinitely accumulating storage?
Always a possibility! 

@hryb-michal What os/browser are you using? I left the app open in chrome for an entire day on OS X and didn't see any artifacts. Let me know where you saw this and I can try debugging it. Thanks!
