### ISSUE TITLE
Can the link ID to be unchanged or auto "+1"? 

### ISSUE THREAD

**Issue by steveyang331** [tone-row/flowchart-fun#71]
Everytime insert a new line, the Link ID will be changed, and then the link id is wrong . we have to modify the all Link ID. 

Is it possible there's a unchanged link ID or auto "+1", after insert a new line ? 

Thank you .

**Comment by rob-gordon** [comment]
You can use a fixed id to avoid this. See #6

'''
Hello
  (myline)
[myline] World
'''

That way adding/removing lines won't require you to adjust your pointer lines.

Hope that helps!

**Comment by rob-gordon** [comment]
I'm going to close this for now but if you think this feature is necessary please open up a github discussion for this feature so I can gauge community support. Thank you!
