### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by sdegutis** [tone-row/flowchart-fun#73]
Github, StackOverflow, and Google all have dark mode now. Can your app have it too? At the very least, `@media (prefers-color-scheme: dark) { ... }`, if not any toggles or anything?

**Comment by sdegutis** [comment]
One solution I found effective is to use CSS variables. At :root (or html), set a bunch of color vars that you use everywhere, and then redefine them inside another :root (or html) that's inside the media query. Then you just have two definition lists of colors, and that's it, and everything automatically just works.

**Comment by rob-gordon** [comment]
We'll definitely add a dark mode in the near future. I'm currently trying to determine the best Design/UX for managing user preferences like this. I'm going to close this issue but if you could show your support for https://github.com/tone-row/flowchart-fun/discussions/32 with an upvote it will help me keep track of what features people are waiting on.

Cheers!

**Comment by sdegutis** [comment]
Well a basic dark mode would help me use your website at night. But all sorts of setting screens and keyboard shortcuts aren't related to that, and are only going to delay that basic usefulness of not being blinded late at night.

**Comment by Schizo** [comment]
I wish this setting would work when saving to PNG too, wanted to use it on a slide with a dark background

**Comment by rob-gordon** [comment]
@sdegutis Proper dark mode has been merged 👍 

@Schizo I made sure dark mode settings were exported as well to give people more options about what they export 👍
