### ISSUE TITLE
Incremental update?

### ISSUE THREAD

**Issue by jameskong9999** [tone-row/flowchart-fun#74]
Is it possible to incremental update the node and the connection from the text without refresh the entire graph?

**Comment by rob-gordon** [comment]
Do you mean prevent the graph from re-drawing itself when you type new nodes/edges in the text?

**Comment by jameskong9999** [comment]
Yes

**Comment by rob-gordon** [comment]
Check out the conversation in https://github.com/tone-row/flowchart-fun/issues/34

I will continue thinking about the best way to do this, but it's somewhat of a tricky problem. If you have thoughts about how this should be done please contribute them to the issue above (or start a [discussion](https://github.com/tone-row/flowchart-fun/discussions) about it).

I'm going to close this issue as a duplicate for now. Thank you for your feedback!
