### ISSUE TITLE
[Show case & suggestion] 

### ISSUE THREAD

**Issue by steveyang331** [tone-row/flowchart-fun#75]
Show case , built Wu xing relationship graph. 

![image](https://user-images.githubusercontent.com/16850883/110446316-fde83e00-80f9-11eb-9c6e-d9cd5ef3e95a.png)

![image](https://user-images.githubusercontent.com/16850883/110449863-96cc8880-80fd-11eb-8473-2239f6b5965a.png)

**Suggestion:**

Why we need type twice the same words, such as,  [Wood]Wood ??

Is it possible only type 1 time words, like backlink [[ ]]  ?

![image](https://user-images.githubusercontent.com/16850883/110446612-58819a00-80fa-11eb-8b61-76489c25a595.png)

it looks like more simple, right ?

**Comment by steveyang331** [comment]
> That functionality would only be useful for first occurence of text in code, the second would still have to look like `[Wood2] Wood`.
> Another limitation I see is that if I'd want to change the name, I'd have to modify all pointers. Might cause trouble when dealing with values we don't know yet, and which we want to insert later ( If we change `[[First Element]]` to `[[Helium]]`, all related pointers `: (First Element)` would have to be renamed too)

I'm not sure if you're a developer of flowchart.fun.  But Yes. if we change the `[[name]]`, all related pointers ` :name `would be renamed ,too. the backlink is working like this.

**Comment by rob-gordon** [comment]
@steveyang331 Thanks for opening this issue!

After giving it some thought, I decided to add a bit of logic to the text parser. Now, before returning the set of nodes and edges, it checks whether any edges have targets that don't resolve. For instance, in:

```
[a] a
[b] b
  edge: (c)
```

the edge has an undefined target `c`. 

If the parser finds edges with an undefined target, it checks to see if the target matches any of the node labels. If there is a match, it points the edge to that node.

I think this will be more intuitive for people than adding a new syntax, and it also means that your example now works with even less text. [Check it out!](https://flowchart.fun/r/Wood%0A%20%20Overcoming%3A%20(Earth)%0A%20%20Generating%3A%20(Fire)%0AFire%20%0A%20%20Overcoming%3A%20(Metal)%0A%20%20Generating%3A%20(Earth)%0AMetal%0A%20%20Overcoming%3A%20(Wood)%0A%20%20Generating%3A%20(Water)%0AWater%0A%20%20Overcoming%3A%20(Fire)%0A%20%20Generating%3A%20(Wood)%0AEarth%0A%20%20Overcoming%3A%20(Water)%0A%20%20Generating%3A%20(Metal))

Thanks for the cool, thoughtful example and suggestions.

**Comment by steveyang331** [comment]
Appreciate you accept my suggestion ! Really great work.
