### ISSUE TITLE
How to add edge lable with default edge ? 

### ISSUE THREAD

**Issue by steveyang331** [tone-row/flowchart-fun#76]
![image](https://user-images.githubusercontent.com/16850883/110454124-d7c69c00-8101-11eb-9c86-b4a40317b6e6.png)

If add " edge label" in new line, there're 2 arrows. 

![image](https://user-images.githubusercontent.com/16850883/110454257-faf14b80-8101-11eb-80d1-b06dc2613925.png)

**Comment by verumsolum** [comment]
Unless I am misunderstanding you, add the label to the same line where you define Fire as a child of Wood.

So for your example, it would be:

```
[Wood]Wood
 Overcoming: (Earth)
 Generating: [Fire]Fire
  Overcoming: (Metal)
  [Earth]Earth
   Overcoming: (Water)
    [Metal]Metal
     Overcoming: (Wood)
     [Water]Water
      : (Wood)
      Overcoming: (Fire)
```

In the example you provided, the `Generating: (Fire)` line and the `[Fire]Fire` line are both at the same indent level, making them both children of `[Wood]Wood`, which is why it gives two arrows.

**Comment by steveyang331** [comment]
> **Edit:** Please disregard. My solution does not work. (My apologies for sending it without checking first).
> 
> ~Unless I am misunderstanding you, add the label to the same line where you define Fire as a child of Wood.~
> 
> ~So for your example, it would be:~
> 
> ```
> [Wood]Wood
>  Overcoming: (Earth)
>  Generating: [Fire]Fire
>   Overcoming: (Metal)
>   [Earth]Earth
>    Overcoming: (Water)
>     [Metal]Metal
>      Overcoming: (Wood)
>      [Water]Water
>       : (Wood)
>       Overcoming: (Fire)
> ```
> 
> ~In the example you provided, the `Generating: (Fire)` line and the `[Fire]Fire` line are both at the same indent level, making them both children of `[Wood]Wood`, which is why it gives two arrows.~

Still Thank you supply a solution. :)

**Comment by rob-gordon** [comment]
Hovering over the edges is very helpful here in diagnosing why edges/nodes exist.

Check out this very simple example.

<img src="https://user-images.githubusercontent.com/159949/110482841-17b46180-80b7-11eb-9b5e-39540e2d6d25.png" width="500"/>
<img src="https://user-images.githubusercontent.com/159949/110482837-16833480-80b7-11eb-8f52-5108c760c2c7.png" width="500"/>

Indentation is a shortcut to creating an edge. So if you want to create a node without creating the edge, create the node with no ident first. Then add your edges separately using pointers (like you've done with `Overcoming` and `Generating`)

This should work: 

```
[Wood] Wood
  Overcoming: (Earth)
  Generating: (Fire)
[Fire] Fire 
  Overcoming: (Metal)
  Generating: (Earth)
[Earth] Earth
  Overcoming: (Water)
  Generating: (Metal)
[Metal] Metal
  Overcoming: (Wood)
  Generating: (Water)
[Water] Water
  Overcoming: (Fire)
  Generating: (Wood)
```

![Screen Shot 2021-03-09 at 9 18 31 AM](https://user-images.githubusercontent.com/159949/110484197-6e6e6b00-80b8-11eb-8a67-6ab7ee7f38eb.png)

**Comment by steveyang331** [comment]
Thank you so much !
