### ISSUE TITLE
way to change side of parent the child goes? 

### ISSUE THREAD

**Issue by zumdar** [tone-row/flowchart-fun#80]
is there a way to change where the child is created? 

it always seems to create the child to the right of the parent. I've noticed you can drag the boxes around, but if you make a 'grandchild' from a child that was dragged to the left , the grandchild, and child automatically move to the right of the parent. 

i think this is a such a great tool for easy flowcharting and maybe mindmapping too!!! 

thank you, and sorry if this is easily done. im still learning.

**Comment by rob-gordon** [comment]
> thank you, and sorry if this is easily done. im still learning.

No, this is a totally fair question. Right now we use a layout algorithm that runs every time the user adds new nodes. Unfortunately, I haven't thought of a good way to determine when people want the layout to reflow, and when they want it to stay fixed.

[On this issue](https://github.com/tone-row/flowchart-fun/issues/34#issuecomment-790682084), someone suggested the idea of "pinning" certain nodes- which I think could work, but I haven't been able to test it yet.

I'm going to close this issue, just so I don't have multiple issues open for the same thing (helps me stay organized) – but please feel free to add comments/suggestions on the issue mentioned above.

I'm glad you like the tool. I appreciate the feedback!

**Comment by rob-gordon** [comment]
(Also the lights you make are awesome!)

**Comment by zumdar** [comment]
wow thank you for responding ! (and the kind words😊) I am new to the collaborative coding world (and really coding in general) and am not sure how to go about asking things like this! It makes me want to get better at coding so i can help contribute to awesome projects like yours.
