### ISSUE TITLE
Text and graph updating 

### ISSUE THREAD

**Issue by ghost** [tone-row/flowchart-fun#89]
0. Default text: 

```
a
b
  edge: (a)
```

1.  
![pAeskknxEv](https://user-images.githubusercontent.com/16850883/111102701-ac233600-8587-11eb-9d52-96a951337451.gif)

Change text` a `to `c` ,
Check the` edge: (a)` and graph text .

Result: the ` edge: (a)`  didn't change to ` edge: (c)` , but the graph is changed to `c` (correct) .

I'm not sure that ` edge: (a)` whether should be updating after  the ` a `  change to `c`  .

2.  
![rGb0ni08bf](https://user-images.githubusercontent.com/16850883/111103670-f0afd100-8589-11eb-9eec-2dea4fdae723.gif)

Back to Default text ,
Change ` edge: (a)`  to ` edge: (c)` 
Check graph and graph in text.
 
Result: `b` still connected `a`

I'm not sure in graph the `b`  whether should be disconnected  `a`, after change  ` edge: (a)`  to ` edge: (c)` .

**Comment by rob-gordon** [comment]
Thank you for opening this issue! Sorry for not replying and the delay in figuring it out.
