### ISSUE TITLE
Feature: questions (decisions) are presented in diamonds

### ISSUE THREAD

**Issue by doctorlard** [tone-row/flowchart-fun#9]
I love it :-) How about a sentence ending in a question mark (?) could be drawn as a diamond, with arrows coming from the corners (for the first three branches anyway). e.g.
```
Is it morning yet?
  yes: get up
  no: go back to sleep
    wake up: (1)
```

**Comment by rob-gordon** [comment]
That's an interesting idea. Someone on hacker news mentioned that these are not actually flowcharts but rather directed graphs. This would help push things in the flowchart direction for sure.

 I'm migrating all issues related to updating/growing the syntax over to Github Discussions so I can gather feedback and gauge support.

Thanks for your suggestion!
