### ISSUE TITLE
Unable to run source code

### ISSUE THREAD

**Issue by andersmandersen** [tone-row/flowchart-fun#91]
Have been using flowchart.fun for that last couple of weeks. But I'm missing a feature to export directly to JPG and PNG. 

I wanted to create my own implementation and submit it as a PR, if it's in the interrest of the owner. 

But I'm having issue with running the source code. I get errors on the external module "@tone-row/slang". 
For example within app/src/App.tsx it can't find Box and Type within "@tone-row/slang". Seems like that can be fixed by changing to "Box Component".

But I'm hitting a rock on Graph.tsx, it's importing layout from "@tone-row/slang". And that is no where to be found. 

I know this issue is a bit misplaced since it's properly a thing with "@tone-row/slang". But I think yarn/npm is downloading the wrong version.

package.json
```
"@tone-row/slang": "^1.2.30",
``` 

Can someone help getting the source code to run.

**Comment by rob-gordon** [comment]
Hey, thank you for your interest! You can definitely submit a PR to export jpg/png. 

I built this on an earlier version of `@tone-row/slang` (a work-in-progress design system utility) which had some components, like `Layout`, that no longer exist. I'll update it to use the latest version, and that should resolve the issues so that you can build successfully.

**Comment by rob-gordon** [comment]
Just merged #92 

Let me know if you're still unable to build it.

In terms of the jpg/png export functionality, I have plans to expand on the app layout in the next weeks so I think it would be best to make the smallest reasonable investment in UI for downloading. In the future I could see a dropdown menu to support this but for now I think something like this would be best.

![Screen Shot 2021-03-18 at 11 18 27 AM](https://user-images.githubusercontent.com/159949/111650544-c8b7ac00-87db-11eb-801e-b7ee13a8b78c.png)

**Comment by andersmandersen** [comment]
Thank you for taking your time! It's now working for me 👯
