### ISSUE TITLE
Radial layouts

### ISSUE THREAD

**Issue by ethanroday** [tone-row/flowchart-fun#93]
First of all, what an awesome tool! Thank you for making this!

Second, would love the ability to toggle between various layouts. Specifically:
  - Radial (I like making mind maps and prefer to visualize them this way)
  - Horizontal hierarchical (current default)
  - Vertical hierarchical (sounds like this has already been requested in #81)

**Comment by rob-gordon** [comment]
@ethanroday Sorry for the delayed response. This functionality is absolutely on the way. Basically my mental roadmap goes:

- add some tests so you don't break parsing logic
- add ability to parse [yaml frontmatter](https://assemble.io/docs/YAML-front-matter.html)
- add front matter option for different layouts
- add some UI for people to toggle between layouts (and persist it!)

I'll leave this issue open until everything's working

**Comment by ethanroday** [comment]
Looking forward to it!

**Comment by rob-gordon** [comment]
Took a few weeks but everything just merged 👍 

Here's an example: https://flowchart.fun/c/H4hQBsEME8HsFcAuAuUACNA7SBbApsmgMYCWATkeHqCMKHgG55nSIAWJmA5umiQM68MnIRjSRRY4uUrUp8tAApGzVh24BKIA

**Comment by ethanroday** [comment]
@rob-gordon Circle layout looks great, but I think I may have underspecified my request. I was hoping for more of a mind-map layout, with a single node in the middle and all of the others branching out around it. Something like [this](https://simplemind.eu/wp-content/uploads/2017/01/birthday-2-associatons-Copy.png) (not the best representation but gets the idea across).

**Comment by rob-gordon** [comment]
I see. There are a few other new layouts available that may get you closer to a mind map. If you click on the Settings Tab you can see the `Layout` select. Off the top of my head I was guess that CoSE (Compound spring embedding) will probably get results closest to a mind map. [An example.](https://flowchart.fun/c/H4hQBsEME8HsFcAuAuUACNA7SBbApsmgMawDOeoIwoeAbngE7SIAWAlpgObppuk8YOAjGkjCRxNgyLgKE+WgAUdRs3ZcAlDz7ChCsQoxEpMuYYzL6TVh05aJe+QcPHps8fMuqbm7fweYHs4KrqYeEl7W6nagQA) 

Hope that helps! I'll keep my eye out for other layouts I can add in the future that support mind maps more explicitly. 👍

**Comment by ethanroday** [comment]
Ahh didn't realize that there were other new layouts available! `cose` works well, as does `concentric`. Thank you!
