### ISSUE TITLE
HTTP ERROR 414 

### ISSUE THREAD

**Issue by matheuschimelli** [tone-row/flowchart-fun#98]
I tried to share a long flowchart I had created but it shows a `414 HTTP Error`. I know that probably this issue is related with the server instead of properly being a issue with flowchart-fun. 

I though a way to solve this error would be:
1. To use the[ Lempel–Ziv–Markov chain algorithm](https://en.wikipedia.org/wiki/Lempel%E2%80%93Ziv%E2%80%93Markov_chain_algorithm) to encode the shareable URL  as the same way [itty-bitty](https://github.com/alcor/itty-bitty) uses.
2. Change the hosting provider or fix the proxy server to allow long URLs(??).

Anyways, thank's for create and maintaining this amazing tool.

**Comment by rob-gordon** [comment]
> To use the Lempel–Ziv–Markov chain algorithm to encode the shareable URL as the same way itty-bitty uses.

This is a great suggestion. I'll look into it!

Out of curiosity, do you know how long the url you tried to share was?

**Comment by heypano** [comment]
@rob-gordon I am also seeing an https certificate issue, wonder if related

```
NET::ERR_CERT_COMMON_NAME_INVALID
Subject: *.aloe.shp.mcafee.com

Issuer: McAfee OV SSL CA 2

Expires on: Apr 24, 2022

Current date: Mar 25, 2021

```

![image](https://user-images.githubusercontent.com/1577139/112508952-683de700-8d66-11eb-9e5b-053dcc259814.png)

**Comment by rob-gordon** [comment]
@heypano Thanks for bringing this to my attention. Looks like [netlify is having CDN issues](https://www.netlifystatus.com/) right now.

**Comment by matheuschimelli** [comment]
> > To use the Lempel–Ziv–Markov chain algorithm to encode the shareable URL as the same way itty-bitty uses.
> 
> This is a great suggestion. I'll look into it!
> 
> Out of curiosity, do you know how long the url you tried to share was?

Yes. Here is the [link](https://flowchart.fun/r/Recupera%C3%A7%C3%A3o%20Judicial%0A%20%20Indeferimento%20do%20processamento%0A%20%20Deferimento%20do%20Processamento%0A%20%20%20%20Publica%C3%A7%C3%A3o%20Edital%20(Art.%2052%C2%A71%C2%B0)%0A%20%20%20%20%20%20Plano%20de%20Recupera%C3%A7%C3%A3o%20(60%20dias)%0A%20%20%20%20%20%20%3A%20(artigo7)%20%0A%20%20%20%20%20%0A%5Bartigo7%5D%20Artigo%207%C2%B0%20ao%20Art.%2020%0A%20%20Recupera%C3%A7%C3%A3o%20Judicial%0A%20%20%20%20Art.%207%C2%B0%3A%20Administrador%20judicial%20verificar%C3%A1%20os%20cr%C3%A9ditos%0A%20%20%20%20%20%20credores%3A%20tem%2015%20dias%20para%20divergir%20ou%20se%20habilitarem%20ao%20cr%C3%A9ditos%0A%20%20%20%20%20%20%20%20Requisitos%20para%20habilita%C3%A7%C3%A3o%20no%20cr%C3%A9dito%20%0A%20%20%20%20%20%20%20%20%20%20%3A%20(artigo9)%0A%20%20%20%20%20%20%20%20%20%20%3A%20(artigo19)%0A%20%20%20%20%20%20%20%20%20%20%3A%20(artigo20)%0A%20%20%20%20%20%20%20%20art.%2010%C2%B0%3A%20se%20o%20credor%20perder%20o%20prazo%20a%20habilita%C3%A7%C3%A3o%20vai%20ser%20tida%20como%20retardat%C3%A1ria%0A%20%20%20%20%20%20%20%20%20%20o%20credor%20que%20tem%20o%20a%20habilita%C3%A7%C3%A3o%20retardat%C3%A1ria%20n%C3%A3o%20tem%20voto%20na%20assembleia%20de%20credores%20exceto%20se%20for%20um%20credor%20de%20t%C3%ADtulo%20de%20cr%C3%A9dito%20de%20rela%C3%A7%C3%A3o%20de%20trabalho%0A%20%20%20%20%20%20Cr%C3%A9ditos%20verificados%0A%20%20%20%20%20%20%20%20O%20adm%20jud%20tem%2045%20dias%20para%20publicar%20edital%20com%20rela%C3%A7%C3%A3o%20de%20cr%C3%A9ditos%20e%20credores%0A%20%20%20%20%20%20%20%20%20%20%3A%20(artigo18)%0A%20%20%20%20%20%20%20%20%20%20o%20edital%20deve%20conter%20o%20local%2C%20hor%C3%A1rio%20e%20prazo%20para%20que%20credor%2C%20o%20devedor%20ou%20seus%20s%C3%B3cios%20ou%20o%20Minist%C3%A9rio%20P%C3%BAblico%20tenham%20acesso%20aos%20documentos%0A%20%20%20%20%20%20%20%20%20%20Se%20n%C3%A3o%20houver%20impugna%C3%A7%C3%A3o%20%0A%20%20%20%20%20%20%20%20%20%20%20%20art.%2014%20se%20n%C3%A3o%20houver%20impugna%C3%A7%C3%A3o%2C%20o%20juiz%20vai%20homologar%20o%20quadro%20de%20credores%20os%20credores%20presentes%20do%20art.%207%C2%B0%20%C2%A72%C2%B0%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3A%20(artigo16)%20%0A%20%20%20%20%20%20%20%20%20%20Impugna%C3%A7%C3%A3o%0A%20%20%20%20%20%20%20%20%20%20%20%20art.8%3A%20Credores%2C%20devedor%2C%20s%C3%B3cio%20ou%20MP%20tem%2010%20dias%20para%20impugnar%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20Art.%2011%3A%20os%20credores%20que%20tiverem%20os%20cr%C3%A9ditos%20impugnados%20v%C3%A3o%20ter%205%20dias%20para%20contestar%20juntando%20documentos%20e%20outras%20provas%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Art.%2012%3A%20%20Passando%205%20dias%20o%20devedor%20vai%20ser%20intimado%20para%20se%20manifestar%20sobre%20a%20contesta%C3%A7%C3%A3o%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3A%20(artigo15)%0A%20%20%20%20%20%20%20%20%20%20%20%20Art.%2013%3A%20a%20impugna%C3%A7%C3%A3o%20ser%C3%A1%20dirigida%20ao%20juiz%20por%20meio%20de%20peti%C3%A7%C3%A3o%20onde%20deve%20ter%20as%20provas%20necess%C3%A1rias%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20Art.%2017%3A%20Da%20decis%C3%A3o%20judicial%20sobre%20a%20impugna%C3%A7%C3%A3o%20caber%C3%A1%20agravo.%0A%20%20Fal%C3%AAncia%0A%20%20%20%20Art.%207%C2%B0-A%3A%20juiz%20instaurar%C3%A1%20incidente%20de%20classifica%C3%A7%C3%A3o%20de%20cr%C3%A9dito%20p%C3%BAblico%20para%20que%20a%20fazenda%20apresente%20ao%20adm%20jud%20ou%20em%20ju%C3%ADzo%20os%20cr%C3%A9ditos%20em%20d%C3%ADvida%20ativa%20%0A%0AFal%C3%AAncia%20(Peti%C3%A7%C3%A3o%20inicial.%20Credor%20a%C3%A7%C3%A3o%20declarat%C3%B3ria%20de%20fal%C3%AAncia)%0A%20%20Defesa%0A%20%20%20%20Intru%C3%A7%C3%A3o%20probat%C3%B3ria%0A%20%20%20%20%20%20Sente%C3%A7a%20Declarat%C3%B3ria%20(art.%2099)%0A%20%20%20%20%20%20%20%20Publica%C3%A7%C3%A3o%20Edital%20(art.%2099%20%C2%A7%C2%B0%20%C3%BAnico)%0A%20%20%20%20%20%20%20%20%20%20Arrecada%C3%A7%C3%A3o%20dos%20bens%0A%20%20%20%20%20%20%20%20%20%20%3A%20(artigo7)%20%0A%20%20%20%20%20%20Senten%C3%A7a%20Denegat%C3%B3ria%0A%0A%5Bartigo9%5D%20Art.%209%C2%B0%20requisitos%20para%20habilita%C3%A7%C3%A3o%20no%20cr%C3%A9dito%0A%20%20o%20nome%2C%20o%20endere%C3%A7o%20do%20credor%20e%20o%20endere%C3%A7o%20em%20que%20receber%C3%A1%20comunica%C3%A7%C3%A3o%20de%20qualquer%20ato%20do%20processo%0A%20%20o%20valor%20do%20cr%C3%A9dito%2C%20atualizado%20at%C3%A9%20a%20data%20da%20decreta%C3%A7%C3%A3o%20da%20fal%C3%AAncia%20ou%20do%20pedido%20de%20recupera%C3%A7%C3%A3o%20judicial%2C%20sua%20origem%20e%20classifica%C3%A7%C3%A3o%0A%20%20a%20indica%C3%A7%C3%A3o%20da%20garantia%20prestada%20pelo%20devedor%2C%20se%20houver%2C%20e%20o%20respectivo%20instrumento%3B%0A%20%20a%20especifica%C3%A7%C3%A3o%20do%20objeto%20da%20garantia%20que%20estiver%20na%20posse%20do%20credor.%0A%20%20Os%20t%C3%ADtulos%20e%20documentos%20que%20legitimam%20os%20cr%C3%A9ditos%20dever%C3%A3o%20ser%20exibidos%20no%20original%20ou%20por%20c%C3%B3pias%20autenticadas%20se%20estiverem%20juntados%20em%20outro%20processo%0A%0A%0A%5Bartigo15%5D%20art.%2015%20%E2%87%92%20transcorridos%20os%20prazos%20previstos%20nos%20arts.%2011%20e%2012%20desta%20Lei%2C%20os%20autos%20de%20impugna%C3%A7%C3%A3o%20ser%C3%A3o%20conclusos%20ao%20juiz%2C%0A%20%20I%20%E2%80%93%20determinar%C3%A1%20a%20inclus%C3%A3o%20no%20quadro-geral%20de%20credores%20das%20habilita%C3%A7%C3%B5es%20de%20cr%C3%A9ditos%20n%C3%A3o%20impugnadas%2C%20no%20valor%20constante%20da%20rela%C3%A7%C3%A3o%20referida%20no%20%C2%A7%202%C2%BA%20do%20art.%207%C2%BA%20desta%20Lei%3B%0A%20%20II%20%E2%80%93%20julgar%C3%A1%20as%20impugna%C3%A7%C3%B5es%20que%20entender%20suficientemente%20esclarecidas%20pelas%20alega%C3%A7%C3%B5es%20e%20provas%20apresentadas%20pelas%20partes%2C%20mencionando%2C%20de%20cada%20cr%C3%A9dito%2C%20o%20valor%20e%20a%20classifica%C3%A7%C3%A3o%3B%0A%20%20III%20%E2%80%93%20fixar%C3%A1%2C%20em%20cada%20uma%20das%20restantes%20impugna%C3%A7%C3%B5es%2C%20os%20aspectos%20controvertidos%20e%20decidir%C3%A1%20as%20quest%C3%B5es%20processuais%20pendentes%3B%0A%20%20IV%20%E2%80%93%20determinar%C3%A1%20as%20provas%20a%20serem%20produzidas%2C%20designando%20audi%C3%AAncia%20de%20instru%C3%A7%C3%A3o%20e%20julgamento%2C%20se%20necess%C3%A1rio.%0A%0A%5Bartigo16%5D%20Art.%2016.%20Para%20fins%20de%20rateio%20na%20fal%C3%AAncia%2C%20dever%C3%A1%20ser%20formado%20quadro-geral%20de%20credores%2C%20composto%20pelos%20cr%C3%A9ditos%20n%C3%A3o%20impugnados%20constantes%20do%20edital%20de%20que%20trata%20o%20%C2%A7%202%C2%BA%20do%20art.%207%C2%BA%20desta%20Lei%2C%20pelo%20julgamento%20de%20todas%20as%20impugna%C3%A7%C3%B5es%20apresentadas%20no%20prazo%20previsto%20no%20art.%208%C2%BA%20desta%20Lei%20e%20pelo%20julgamento%20realizado%20at%C3%A9%20ent%C3%A3o%20das%20habilita%C3%A7%C3%B5es%20de%20cr%C3%A9dito%20recebidas%20como%20retardat%C3%A1rias.%0A%0A%5Bartigo18%5D%20Art.%2018.%20%0A%20%20O%20administrador%20judicial%20ser%C3%A1%20respons%C3%A1vel%20pela%20consolida%C3%A7%C3%A3o%20do%20quadro-geral%20de%20credores%2C%20a%20ser%20homologado%20pelo%20juiz%2C%20com%20base%20na%20rela%C3%A7%C3%A3o%20dos%20credores%20a%20que%20se%20refere%20o%20art.%207%C2%BA%20%2C%20%C2%A7%202%C2%BA%20%2C%20desta%20Lei%20e%20nas%20decis%C3%B5es%20proferidas%20nas%20impugna%C3%A7%C3%B5es%20oferecidas.%0A%20%20%20%20Par%C3%A1grafo%20%C3%BAnico.%20O%20quadro-geral%2C%20assinado%20pelo%20juiz%20e%20pelo%20administrador%20judicial%2C%20mencionar%C3%A1%20a%20import%C3%A2ncia%20e%20a%20classifica%C3%A7%C3%A3o%20de%20cada%20cr%C3%A9dito%20na%20data%20do%20requerimento%20da%20recupera%C3%A7%C3%A3o%20judicial%20ou%20da%20decreta%C3%A7%C3%A3o%20da%20fal%C3%AAncia%2C%20ser%C3%A1%20juntado%20aos%20autos%20e%20publicado%20no%20%C3%B3rg%C3%A3o%20oficial%2C%20no%20prazo%20de%205%20(cinco)%20dias%2C%20contado%20da%20data%20da%20senten%C3%A7a%20que%20houver%20julgado%20as%20impugna%C3%A7%C3%B5es.%0A%0A%5Bartigo19%5D%20Artigo%2019%0A%20%20Art.%2019.%20O%20administrador%20judicial%2C%20o%20Comit%C3%AA%2C%20qualquer%20credor%20ou%20o%20representante%20do%20Minist%C3%A9rio%20P%C3%BAblico%20poder%C3%A1%2C%20at%C3%A9%20o%20encerramento%20da%20recupera%C3%A7%C3%A3o%20judicial%20ou%20da%20fal%C3%AAncia%2C%20observado%2C%20no%20que%20couber%2C%20o%20procedimento%20ordin%C3%A1rio%20previsto%20no%20C%C3%B3digo%20de%20Processo%20Civil%2C%20pedir%20a%20exclus%C3%A3o%2C%20outra%20classifica%C3%A7%C3%A3o%20ou%20a%20retifica%C3%A7%C3%A3o%20de%20qualquer%20cr%C3%A9dito%2C%20nos%20casos%20de%20descoberta%20de%20falsidade%2C%20dolo%2C%20simula%C3%A7%C3%A3o%2C%20fraude%2C%20erro%20essencial%20ou%2C%20ainda%2C%20documentos%20ignorados%20na%20%C3%A9poca%20do%20julgamento%20do%20cr%C3%A9dito%20ou%20da%20inclus%C3%A3o%20no%20quadro-geral%20de%20credores.%0A%20%20%20%20%C2%A7%201%C2%BA%20A%20a%C3%A7%C3%A3o%20prevista%20neste%20artigo%20ser%C3%A1%20proposta%20exclusivamente%20perante%20o%20ju%C3%ADzo%20da%20recupera%C3%A7%C3%A3o%20judicial%20ou%20da%20fal%C3%AAncia%20ou%2C%20nas%20hip%C3%B3teses%20previstas%20no%20art.%206%C2%BA%20%2C%20%C2%A7%C2%A7%201%C2%BA%20e%202%C2%BA%20%2C%20desta%20Lei%2C%20perante%20o%20ju%C3%ADzo%20que%20tenha%20originariamente%20reconhecido%20o%20cr%C3%A9dito.%0A%20%20%20%20%20%20%C2%A7%202%C2%BA%20Proposta%20a%20a%C3%A7%C3%A3o%20de%20que%20trata%20este%20artigo%2C%20o%20pagamento%20ao%20titular%20do%20cr%C3%A9dito%20por%20ela%20atingido%20somente%20poder%C3%A1%20ser%20realizado%20mediante%20a%20presta%C3%A7%C3%A3o%20de%20cau%C3%A7%C3%A3o%20no%20mesmo%20valor%20do%20cr%C3%A9dito%20questionado.%0A%0A%0A%5Bartigo20%5D%20Artigo%2020%0A%20%20Art.%2020.%20As%20habilita%C3%A7%C3%B5es%20dos%20credores%20particulares%20do%20s%C3%B3cio%20ilimitadamente%20respons%C3%A1vel%20processar-se-%C3%A3o%20de%20acordo%20com%20as%20disposi%C3%A7%C3%B5es%20desta%20Se%C3%A7%C3%A3o.%0A%0A)

It has about `9,678 bytes`.

**Comment by rob-gordon** [comment]
@matheuschimelli Just merged an update. We're now using [lz-string](https://github.com/pieroxy/lz-string).

I'm not sure if this solution will be good enough in the long-term. For instance, your flowchart compressed is still ~3000 characters, which according to this [SO answer](https://stackoverflow.com/a/417184/903980) would still be too large in Edge or Internet Explorer.

But either way, this is definitely an improvement. Thank you for the suggestion!
